from ..itertoolz import cons as cons, getter as getter, pluck as pluck
from typing import Any

class EqualityHashKey:
    key: Any = ...
    item: Any = ...
    def __init__(self, key: Any, item: Any) -> None: ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

def unzip(seq: Any): ...
