from .compatibility import PY3 as PY3
from .functoolz import has_keywords as has_keywords, has_varargs as has_varargs, is_arity as is_arity, is_partial_args as is_partial_args, num_required_args as num_required_args
from typing import Any

module_info: Any

def num_pos_args(sigspec: Any): ...
def get_exclude_keywords(num_pos_only: Any, sigspec: Any): ...
def signature_or_spec(func: Any): ...
def expand_sig(sig: Any): ...

signatures: Any

def create_signature_registry(module_info: Any = ..., signatures: Any = ...) -> None: ...
def check_valid(sig: Any, args: Any, kwargs: Any): ...
def check_partial(sig: Any, args: Any, kwargs: Any): ...
def check_arity(n: Any, sig: Any): ...
def check_varargs(sig: Any): ...
def check_keywords(sig: Any): ...
def check_required_args(sig: Any): ...
