from typing import overload, Any, Callable, Iterable, Iterator, Mapping, List, Optional, Tuple, TypeVar, Union
from ._typing import MappingFactory
from ._typing import T, U, V

def merge(*dicts: Any, **kwargs: Any): ...
def merge_with(func: Any, *dicts: Any, **kwargs: Any): ...
def valmap(func: Any, d: Any, factory: Any = ...): ...
def keymap(func: Any, d: Any, factory: Any = ...): ...
def itemmap(func: Any, d: Any, factory: Any = ...): ...
def valfilter(predicate: Any, d: Any, factory: Any = ...): ...
def keyfilter(predicate: Any, d: Any, factory: Any = ...): ...
def itemfilter(predicate: Any, d: Any, factory: Any = ...): ...
def assoc(d: Mapping[T, U], key: T, value: U, factory: MappingFactory[T, U] = ...) -> Mapping[T, U]: ...
def dissoc(d: Mapping[T, U], *keys: T, **kwargs: Any) -> Mapping[T, U]: ...
def assoc_in(d: Any, keys: Any, value: Any, factory: Any = ...): ...
def update_in(d: Any, keys: Any, func: Any, default: Optional[Any] = ..., factory: Any = ...): ...
def get_in(keys: Any, coll: Any, default: Optional[Any] = ..., no_default: bool = ...): ...
